# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_auto_20180424_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='gender',
            new_name='dormitory',
        ),
    ]
