# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_auto_20180424_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='character',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='poll',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
    ]
