# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0005_auto_20180425_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='party_number',
            field=models.IntegerField(default=0),
        ),
    ]
