# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0006_character_party_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='party_number',
        ),
    ]
